### ISSUE TITLE
 Clarification regarding  ORFs and protein hits plot

### ISSUE THREAD

**Issue by acontrerasg** [clemgoub/TE-Aid#2]
Hello,
Thanks for developing this useful tool. 
I am playing around with it and I came out with a plot  with some arrowheads and crosses.
My guess is that the arrowheads are just small arrows that aren't big enough to display the line and the crosses are actually two opposing small arrows. But it will be nice to hear if my thoughts are correct or actually arrowheads and crosses mean something different. 

Below the plot I refer to:

![image](https://user-images.githubusercontent.com/37411686/163268002-76a7aec0-1341-46a8-9160-54a275f44582.png)

Thanks!
Adrian

**Comment by clemgoub** [comment]
Hello Adrian! 

You are completely right! The crosses are just arrowheads (short palindromic stretches) and the single arrowheads are short, in the same direction, repeats. These arrows are the direct mapping in 1D of the dot-plot. I did not filter on size for these representations, but you can know exactly by printing the dotplot table with `-t`.

Thanks for your feedback!

Best,

Clément
