### ISSUE TITLE
Missing component to detect ORFs?

### ISSUE THREAD

**Issue by piosierra** [clemgoub/TE-Aid#3]
Hello,

I am running TE-Aid with the default options, but it doesn't seem to find any ORF in any of my consensus sequences. On the exit I see these messages (indented by me). Do they mean that I am missing some requirement? I have (to the best of my knowledge) emboss installed. Is there a particular component I might be missing?

Thanks.

```
TE -> genome blastn e-value:   10e-8
full length min ratio:         0.9
hits transparency:             0.3
full length hits transparency: 0.9
        grep: plots/TE.orfs: No such file or directory
        no ORF detected, skipping blastp...
[1] "R: ploting genome blastn results and computing coverage..."
[1] "consensus length:  7271 bp"
[1] "R: ploting self dot-plot and orf/protein hits..."
        [1] "no orf to plot..."
        Warning message:
        In file(file, "rt") :
            cannot open file 'plots/orftetable': No such file or directory
null device 
          1 
Done! The graph (.pdf) can be found in the output folder: plots
```

**Comment by piosierra** [comment]
Hello Cément,

I did some debugging and the problem was in the wrapper script I used to batch call TE-Aid on the HPC. Due to it the call to getorf was not working as expected, and no result was produced. I modified it and now it is working properly. 

Thanks a lot for your support and the tool.

**Comment by clemgoub** [comment]
No problem! Glad you found a solution!

Cheers,

Clément
