### ISSUE TITLE
No Output generated

### ISSUE THREAD

**Issue by roperete** [clemgoub/TE-Aid#4]
Dear Clement, 

I seem to encounter many errors that lead to a no-output result. This is the error message:

_query:
ref genome:
TE -> genome blastn e-value:   10e-8
full length min ratio:         0.9
hits transparency:             0.3
full length hits transparency: 0.9
grep: ./TE.orfs: No such file or directory
no ORF detected, skipping blastp...
Warning message:
NAs introduced by coercion
Warning message:
NAs introduced by coercion
Warning message:
NAs introduced by coercion
Error in file(filename, "r", encoding = encoding) :
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'NA/consensus2genome.R': No such file or directory
Execution halted
rm: cannot remove './TE.db*': No such file or directory
Done! The graph (.pdf) can be found in the output folder: ._

There is no .pdf file produced

**Comment by clemgoub** [comment]
Hello! 

I'm sorry for your trouble with TE-Aid... It seems that the input query and genome are not found (empty variables) by the program. Can you post the command line you used?

Cheers,

Clément

**Comment by roperete** [comment]
Hi Clément!

It was a _silly_ mistake from my side, I was trying to use TE-Aid on my file with all the transposons (multi-fasta). I think It will work if I use TE-Aid sequence by sequence? 

Thanks!

**Comment by clemgoub** [comment]
Indeed! Nothing silly actually, I should work on a version that handle multi-fasta! It'll come!

Cheers,

Clément
