### ISSUE TITLE
Better to move "file1" and "file2" into $OUTPUT

### ISSUE THREAD

**Issue by qjiangzhao** [clemgoub/TE-Aid#6]
Hi Clément,

I found it would be better to move these two temporary files including "file1" and "file2" to $OUTPUT. Especially when TE Aid is executed under multiple threads environment. 

  #join orfs with their prot hit
  sort -k1,1 $OUTPUT/TE.orfs.R > file1
  sort -k1,1 $OUTPUT/TE.blastp.out > file2
  join -a1 -11 -21 file1 file2 | \

Yours sincerely
Jiangzhao

**Comment by clemgoub** [comment]
Hi Jiangzhao!

Thanks for the comment. If you are up to it, I suggest that you implement the change in a new branch, and submit a pull request. This way, your contribution will be credited on Github!

Otherwise, I'll take a note to implement it -- probably later this week.

Best,

Clément

**Comment by qjiangzhao** [comment]
Hi Clément,

I made the change and uploaded it to a new branch. You can check it and decide if to integrate the modification into your main or master branch.

Yours sincerely
Jiangzhao
